image: oven/bun:latest

stages:
  - lint
  - build

before_script:
  - curl -fsSL https://bun.sh/install | bash
  - export PATH="$HOME/.bun/bin:$PATH"
  - bun install

lint:
  stage: lint
  script:
    - bun run lint

build:
  stage: build
  script:
    - bun run build
