name: Bun CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-testing:
    runs-on: docker
    container:
      image: oven/bun:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: bun install

      - name: Running lint
        run: bun run lint

      - name: Running build
        run: bun run build
