name: Sync to GitHub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from Gitea
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitHub mirror-main
        run: |
          git remote add github https://vivy-agent:${{ secrets.GH_TOKEN }}@github.com/rafiarrafif/SyzneTV-frontend.git
          git push github HEAD:mirror-main --force
